   name: build-test
   on: [pull_request]

   jobs: 
      build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node: ['16']
        steps: 
          - uses: actions/checkot@v2 
          - name: setup node 16
            uses: actcions/setup-node@v2 
            with:
              node-version: 16.x
          - run: npm install
          - run: npm run lint



 